name: DevSecOps Agent Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-security-scan:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clone DevSecOps Project
        run: git clone https://github.com/sinhaayush992-netizen/DevSecOps-Agent.git
 
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Build Project
        run: mvn -f DevSecOps-Agent/pom.xml clean install
 
      # SonarCloud Scan
      - name: SonarCloud Scan
        run: |
         mvn sonar:sonar \
          -Dsonar.projectKey=sinhaayush992-netizen_DevSecOps-Agent \
          -Dsonar.organization=sinhaayush992-netizen \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      
 
      # Snyk Scan
      - name: Install snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Security Scan
        run: snyk test --file=sinhaayush992-netizen/DevSecOps-Agent/pom.xml
      #  env:
       #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}