name: DevSecOps Agent Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-security-scan:
    runs-on: ubuntu-latest
 
    steps:
 
    # Checkout Main Repo
    - name: Checkout Code
      uses: actions/checkout@v3
 
    #Checkout DevSecOps Agent Repo
    - name: Checkout DevSecOps Project
      uses: actions/checkout@v4
      with:
        repository: sinhaayush992-netizen/DevSecOps-Agent
        path: DevSecOps-Agent
 
    #Verify Files
    - name: Verify Repo
      run: ls -R
 
    #Setup Java
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
 
    #Build Project
    - name: Build Project
      run: mvn -f DevSecOps-Agent/pom.xml clean install
 
    #SONAR SCAN
    - name: SonarCloud Scan
      run: |
        mvn -f DevSecOps-Agent/pom.xml sonar:sonar \
        -Dsonar.projectKey=sinhaayush992-netizen_DevSecOps-Agent \
        -Dsonar.organization=sinhaayush992-netizen \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
    #SNYK SCAN
    - name: Install Snyk
      run: npm install -g snyk
 
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
    - name: Snyk Security Scan
      run: snyk test --file=DevSecOps-Agent/pom.xml
      continue-on-error: true
 
    - name: Generate Snyk Report
      run: snyk test --file=DevSecOps-Agent/pom.xml --json > snyk-report.json || true
      continue-on-error: true
 
    #Upload Report
    - name: Upload Snyk Report
      uses: actions/upload-artifact@v4
      with:
        name: snyk-report
        path: snyk-report.json
 
    #RUN AI ANALYZER AGENT
    - name: Build Analyzer Agent
      run: mvn clean package
    - name: Check Target Folder
      run: ls target
 
    - name: Run Analyzer Agent (AI + Jira)
      run: java -jar target/*.jar
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
 